/* Content based on Lin Zheng (2024), pp.101–111. No external requests. */
const fig=(file,caption,cls='')=>`<figure class="${cls}"><button class="zoom" data-image="${file}" data-caption="${caption}" aria-label="放大图像：${caption}"><img src="assets/images/${file}" alt="${caption}"></button><figcaption>${caption}</figcaption></figure>`;
const head=(label,title)=>`<div class="eyebrow">${label}</div><h1>${title}</h1>`;
const end=text=>`<div class="takeaway">${text}</div>`;
const center=html=>`<div class="center">${html}</div>`;
const split=(a,b,cls='')=>`<div class="split ${cls}"><div>${a}</div><div>${b}</div></div>`;
const city=`<div class="city" role="img" aria-label="城中村有机生长概念示意"><b style="--h:52%"></b><b style="--h:85%"></b><b style="--h:66%"></b><b style="--h:95%"></b><b style="--h:74%"></b><b style="--h:60%"></b></div>`;
const frame=(html,note)=>({html,note});
const observePage=(stage,body,cls='')=>`<section class="observation-page ${cls}" data-observe-stage="${stage}"><div class="obs-texture" aria-hidden="true"></div><div class="obs-number">03</div><div class="obs-heading"><h1>从《阿珍爱上了阿强》开始，<br>五条人为什么“<em>不对劲</em>”？</h1><p>先别急着解释，看看这些东西为什么会同时出现。</p></div>${body}<div class="obs-stage-mark"><b>${stage+1}</b><span>/ 7</span></div></section>`;
const flow=`<div class="flow"><div>未完成的现代性<small>重新界定概念，反拨线性现代性</small></div><i>↓</i><div>珠三角城中村 / 城中村美学</div><i>↓</i><div class="branch"><span>山寨<small>文化生产方式 / 商品出口</small></span><span>打口<small>获取世界的路径 / 文化进口</small></span></div><small class="red">文化动因与表现方式</small><i>↓</i><div>地方与全球重新组合</div><i>↓</i><div class="red">全球地方 / 低端全球化 / 全球南方<small>回到中国式“未完成的现代性”</small></div></div>`;
const network=`<div class="network"><svg viewBox="0 0 1400 580" role="img" aria-label="广州小北、香港重庆大厦、非洲和中东的跨国联系示意"><defs><pattern id="grid" width="100" height="80" patternUnits="userSpaceOnUse"><path d="M100 0H0V80" fill="none" stroke="#ffffff16"/></pattern></defs><rect width="1400" height="580" fill="url(#grid)"/><g class="routes"><path d="M1050 150 Q650 -30 370 190"/><path d="M1050 150 Q710 560 260 380"/><path d="M1050 150 Q1240 250 1090 380"/><path d="M1090 380 Q700 600 260 380"/></g><g fill="#eb4938"><circle cx="1050" cy="150" r="11"/><circle cx="1090" cy="380" r="11"/><circle cx="370" cy="190" r="11"/><circle cx="260" cy="380" r="11"/></g><g class="map-text"><text x="965" y="110">广州 · 小北</text><text x="965" y="435">香港 · 重庆大厦</text><text x="230" y="140">中东 / 阿拉伯商人</text><text x="125" y="445">非洲 / 跨国贸易</text></g></svg><div class="network-bottom"><strong>低资本投入 / 非正式经济 / 跨国流动</strong><span>麦高登：“低端全球化”</span></div><small>跨国联系示意 · 非精确地理底图或定量贸易流</small></div>`;
const scenes=[
{label:'先认识五条人',type:'课堂导入',source:'导入素材；《阿珍爱上了阿强》不作为论文核心分析文本。',theme:'dark',time:'2:20',frames:[
frame(`<button class="cover-enter" data-action="start" aria-label="点击或按空格进入课堂报告"><img src="assets/images/cover-unfinished-modernity.png" alt="未完成的现代性：五条人与珠三角城中村美学，古典社会理论互动式课堂报告封面"></button>`,'封面先停留，让同学看见城中村、塑料袋、五条人与“未完成的现代性”之间的视觉联系。按空格或点击画面进入开场视频；如果本地视频不存在，则自动转入真实演出图与海报的视觉序列。'),
frame(`<div class="video-intro-page"><img class="video-intro-art" src="assets/images/video-intro-page.png" alt="从《阿珍爱上了阿强》开始，品味五条人的美学"><div class="intro-video-slot"><video class="intro-inline-video" src="assets/video/opening.mp4" controls playsinline preload="metadata" hidden aria-label="《阿珍爱上了阿强》视频片段"></video></div><button class="intro-video-trigger" data-action="intro-video" aria-label="播放《阿珍爱上了阿强》视频"><span>播放视频</span></button></div>`,'第二页先停在视频入口，不自动播放。点击画面中央的播放键开始播放《阿珍爱上了阿强》片段；播放期间空格暂停或继续，右箭头进入开场问题。先让同学感受声音、场景与人物，不急着解释。'),
frame(observePage(0,`<div class="obs-layout"><figure class="obs-main-image"><img src="assets/images/mv-wide.jpg" alt="《阿珍爱上了阿强》视频中的旧建筑与乐队演出场景"><figcaption>《阿珍爱上了阿强》视频定格</figcaption></figure><div class="obs-prompt"><span>OBSERVE</span><h2>你刚才<br>看到了什么？</h2><small>SPACE → 继续观察</small></div></div>`),'先停在画面，不解释。邀请同学回忆刚才看到的声音、人物与空间。'),
frame(observePage(1,`<div class="obs-analysis"><div class="obs-media"><img src="assets/images/mv-wide.jpg" alt="旧建筑中的乐队演出场景"><span class="focus-box place"></span><small>从画面里先抽取“地方”</small></div><div class="obs-extract"><span class="obs-kicker">01 / 地方</span><h2>县城<br><i>/</i> 城中村</h2><p>海丰，广州，珠三角。</p></div></div>`),'第一层只说空间：旧建筑、街头招牌、县城与城中村经验。'),
frame(observePage(2,`<div class="obs-analysis"><div class="obs-media portrait"><img src="assets/images/mv-duo.jpg" alt="五条人演唱与演奏画面"><span class="focus-box voice"></span><small>声音没有离开它生长的地方</small></div><div class="obs-extract"><span class="obs-kicker">02 / 声音</span><h2>方言<br><i>/</i> 地方性</h2><p>海丰话并没有因为进入城市而消失。</p></div></div>`),'第二层转到声音：他们很地方，但同时在做现代流行音乐。不要展开语言学。'),
frame(observePage(3,`<div class="obs-analysis"><div class="obs-media portrait"><img src="assets/images/mv-guitar.jpg" alt="五条人使用电吉他演奏"><span class="focus-box guitar"></span><small>现代乐器进入地方经验</small></div><div class="obs-extract blue"><span class="obs-kicker">03 / 流行文化</span><h2>电吉他<br>港风<br>世界音乐</h2><p>县城经验，与现代流行文化同时存在。</p></div></div>`),'第三层只制造并置感：电吉他、港风、世界音乐，不提前解释打口。'),
frame(observePage(4,`<div class="obs-analysis"><div class="obs-media street"><img src="assets/images/mv-duo.jpg" alt="旧工业空间中的五条人演出"><img class="salon-fragment" src="assets/images/salon-front.png" alt="梦幻丽莎发廊视觉局部"><small>市井趣味，被带进作品与舞台</small></div><div class="obs-extract rough"><span class="obs-kicker">04 / 趣味</span><h2>俗 / 土<br>/ 市井</h2><strong>先锋<i>？</i></strong></div></div>`),'第四层先出现俗、土、市井，再在旁边留下“先锋？”这个疑问，不下结论。'),
frame(observePage(5,`<div class="obs-recombine"><img src="assets/images/mv-wide.jpg" alt="淡化的演出背景"><div class="relation r1"><span>乡土</span><b>×</b><em>都市</em></div><div class="relation r2"><span>本土</span><b>×</b><em>全球</em></div><div class="relation r3"><span>俗</span><b>×</b><em>先锋</em></div><div class="relation r4"><span>旧</span><b>×</b><em>新</em></div><small>不是替代，而是混杂、叠加与交叉。</small></div>`),'把前面零散出现的元素重新组织成四组关系。强调叉号不是互相排斥，而是同时存在。'),
frame(observePage(6,`<div class="obs-theory"><div class="relations-echo">乡土 × 都市　　本土 × 全球　　俗 × 先锋　　旧 × 新</div><div class="modern-line"><span>传统</span><i>⟶</i><span>现代</span><b>／</b></div><h2>如果现代性是一条<br>从“传统”走向“现代”的直线，</h2><h3>五条人为什么偏偏<br><em>把两端混在了一起？</em></h3><p>也许“不对劲”的不是五条人，<br>而是我们原先理解现代性的方式。</p><small>林峥给出的回答是：<b>“未完成的现代性”</b></small></div>`),'最后提出真正的理论问题。停顿后点出下一页的概念名称，但不要解释。再按一次空格进入论文核心观点。')
]},
{label:'现代性的直线',type:'概念入口 · 课堂转述',source:'第一节 pp.101—102；本页呈现论文所反思的线性现代性想象。',theme:'paper',time:'1:15',frames:[
frame(`<section class="theory-road scene04"><div class="theory-texture" aria-hidden="true"></div><div class="theory-page-no">04</div><div class="theory-heading"><span>THE ROAD TO MODERNITY</span><h1>我们通常怎样想象现代性？</h1></div><div class="road-question">我们离“完成”还有多远？</div><div class="development-road"><div class="road-line" aria-hidden="true"></div><div class="road-pair p1"><span>传统</span><i>→</i><b>现代</b></div><div class="road-pair p2"><span>农村</span><i>→</i><b>城市</b></div><div class="road-pair p3"><span>地方</span><i>→</i><b>全球</b></div><div class="road-pair p4"><span>非正规</span><i>→</i><b>正规</b></div><div class="road-pair p5"><span>欠发达</span><i>→</i><b>发达</b></div><div class="road-pair p6"><span>低端</span><i>→</i><b>高端</b></div><div class="finish-marker"><strong>FINISH</strong><em>完成</em></div></div><div class="theory-conclusion">即使开始看见“边缘”，<br>也可能仍在使用“中心”的尺子。</div></section>`,'这一页先呈现我们熟悉的直线想象：传统、农村、地方、非正规、欠发达、低端，都被放在同一条通往完成的道路上。强调“欠发达”“低端”看似描述了边缘经验，却仍默认发达、高端是唯一终点。')
]},
{label:'取消终点',type:'文章主要观点 · 课堂转述',source:'第一节 pp.101—102；“未完成”不是程度不足，而是不同质的现代性。',theme:'paper',time:'1:40',frames:[
frame(`<section class="theory-road scene05 is-linear"><div class="theory-texture" aria-hidden="true"></div><div class="theory-page-no">05</div><div class="theory-heading"><span>BEYOND THE FINISH LINE</span><h1>如果现代性没有终点？</h1></div><div class="development-road compact"><div class="road-line" aria-hidden="true"></div><div class="road-pair p1"><span>传统</span><i>→</i><b>现代</b></div><div class="road-pair p2"><span>农村</span><i>→</i><b>城市</b></div><div class="road-pair p3"><span>地方</span><i>→</i><b>全球</b></div><div class="road-pair p4"><span>非正规</span><i>→</i><b>正规</b></div><div class="finish-marker"><strong>FINISH</strong><em>完成</em></div></div><div class="old-equation">未完成 <i>→</i> 完成</div><div class="space-hint">SPACE　删除终点</div></section>`,'延续上一页的直线，先停顿。这里只保留四组方向和“完成”的终点，让同学看到：即使换了对象，现代性仍被理解为同一条路。按一次空格取消终点。'),
frame(`<section class="theory-road scene05 is-open"><div class="theory-texture" aria-hidden="true"></div><div class="theory-page-no">05</div><div class="theory-heading"><span>BEYOND THE FINISH LINE</span><h1>如果现代性没有终点？</h1></div><svg class="branching-road" viewBox="0 0 1400 430" preserveAspectRatio="none" aria-label="原本单向的发展直线向多个方向分叉、弯曲和交错"><path class="road-origin" d="M18 214 C260 214 405 214 565 214"/><path d="M545 214 C720 205 805 75 1010 92 S1260 145 1380 54"/><path d="M545 214 C725 230 800 340 1010 326 S1240 242 1382 286"/><path d="M545 214 C735 155 860 155 1040 218 S1250 390 1382 382"/><path d="M545 214 C760 285 870 245 1045 155 S1255 82 1380 150"/></svg><div class="finish-marker erased"><strong>FINISH</strong><em>完成</em></div><div class="unfinished-title"><span>UNFINISHED MODERNITY</span><h2>未完成的现代性</h2></div><div class="unfinished-sentences"><p>“未完成”不是“尚未完成”。</p><strong>甚至根本不需要被完成。</strong></div><div class="quality-claim">“未完成的现代性”与“完成的现代性”<br>不是发展阶段的差异，<br><b>而是不同质的现代性。</b></div><div class="equation-shift"><del>未完成 → 完成</del><strong>未完成 <i>≠</i> 完成</strong><small>不是“还没到终点”，而是另一种现代性。</small></div><div class="next-question"><span>城中村 · 山寨 · 打口</span><p>那么，<br>“另一种现代性”究竟长什么样？</p></div></section>`,'终点被划掉，直线转为分叉。讲清论文核心判断：“未完成”并不是“尚未完成”，甚至不需要被完成；它与“完成的现代性”不是阶段差异，而是不同质的现代性。再按空格进入城中村。')
]},
{label:'城中村：空间形态',type:'作者观点 · 课堂转述',source:'第二节 pp.102—105；握手楼 p.104，引李培林（2002）；政策比较 pp.103—104。',theme:'paper',time:'2:30',frames:[
frame(head('SPACE / 珠三角','在城市里面，生长。')+split(city+`<small>自制空间示意 · 非具体村落复原</small>`,`<h2>城乡二元体制<br>× 快速城市化</h2><p>不平衡发展的产物</p><div class="rule"></div><h3>从“等待改造”的空间<br>看见流动与民间主动性</h3>`),'先交代结构背景。作者没有把城中村当作自然发生的自由空间：它与城乡二元体制、城市化和劳动力流动有关。廉租空间让劳动者栖身，也滋养艺术活动。'),
frame(head('HANDSHAKE BUILDINGS / 握手楼','政府规则，如何被日常使用？')+`<div class="mechanism">政府规则 <i>→</i> 村民加建 <i>→</i> 租金收益</div><div class="handshake"><div class="building left"><span>住宅 / 出租</span></div><div class="gap">规则间隙</div><div class="building right"><span>住宅 / 出租</span></div></div><div class="diagram-caption">底层留出间隔 · 上部仍可调整</div>`,'Space出现握手楼示意。原文谈宅基地间隔、二层以上外探与加盖。原文数值来自既有研究，不作为当下法规。'),
frame(head('HANDSHAKE BUILDINGS / 握手楼','在规则间隙中争取空间。')+`<div class="mechanism">规则 <i>↔</i> 加建 / 外探 <i>↔</i> 租金与罚款成本</div><div class="handshake growing"><div class="building left"><span>二层以上外探</span></div><div class="gap">一线天</div><div class="building right"><span>层层加盖</span></div></div>`+end('不正面对抗，却不断调整。'),'Space建筑向上、向内生长。村民在收益与罚款间计算，这体现作者讨论的灵活应对。不将这一机制描述为没有风险的理想治理。'),
frame(head('TWO FORCES / 两种力量','政策弹性 ＋ 民间自组织')+split(city,`<h2>握手楼<br>烂尾楼 / 遮丑墙</h2><p>空间经验，被提炼为审美表达。</p><p class="red">生活中的悲剧并未消失。</p><small>《烂尾楼》中的失踪、破产与流离失所，<br>仍是作品的现实背景。</small>`),'Space后强调双重合力：政策的包容与支持、民间智慧和主动性。再用《烂尾楼》与遮丑墙说明五条人怎样转化这些空间经验。转场：一只塑料袋把这种气质串联起来。')
]},
{label:'塑料袋：视觉母题',type:'作者观点 · 课堂转述',source:'原文 p.103 引设计师胡子；p.104“塑料袋式的生活哲学”。',theme:'dark',time:'1:15',frames:[
frame(head('A MOTIF / 视觉母题','一只不守规则的塑料袋')+split(fig('tour-posters.jpg','2017年巡演海报｜胡子设计工作室 / 新周刊'),`<h2>高楼 / 笔直<br>整齐 / 规划</h2><div class="rule"></div><p>一只随意飘动的塑料袋，<br>与严谨的都市形成拉扯。</p>`),'用真实巡演海报解释张力：不是只有廉价，而是与严谨高楼不同的飘动、暧昧、不直接反叛。可点击看清两种海报形式。'),
frame(head('A MOTIF / 视觉母题','随意 · 暧昧 · 游动')+split(fig('bag-design.jpg','五条人塑料袋视觉｜胡子设计工作室'),`<div class="motif-chain">塑料袋 <i>↓</i> 握手楼 <i>↓</i> 走鬼 <i>↓</i> 山寨 / 打口</div>`)+end('课堂以此连接实践气质，不另立“塑料袋现代性”理论。'),'Space把几个对象串起来。作者确有“塑料袋式的生活哲学”的表述，但我们不扩写成独立理论。转场：这种气质怎么进入作品的生产？')
]},
{label:'山寨：文化生产',type:'作者观点 · 课堂转述',source:'第三节 pp.105—108；TIME 修改过程 p.106；图一—五。',theme:'paper',time:'3:00',frames:[
frame(head('PRODUCTION / 文化动因与表现方式','山寨：让熟悉的形式变形。')+`<div class="compare">${fig('time-initial.png','初版：直接挪用 TIME 标志｜原文图二')}<div class="between">协商<i>→</i><small>知识产权顾虑</small></div>${fig('time-final.png','修改版：更“山寨”｜原文图一')}</div>`,'先展示论文真实两版海报。原文说最初直接挪用TIME，哈佛校方提出知识产权顾虑，于是改得更“山寨”，不是凭空设计错误效果。'),
frame(head('PARODY / 不正面对抗的游戏','挪用 → 协商 → 变形')+split(fig('time-final.png','讲座海报修改版｜设计：胡子；原文图一'),`<h2>模仿　戏仿<br>组合　游戏<br><span class="red">再创造</span></h2><p>从熟悉的形式中，产生新的意义。</p><small>分析审美机制，不把所有仿冒行为一概正当化。</small>`),'Space：解释戏仿有主体意识和幽默，不能只总结成模仿变原创。作者还区分它与媚俗、詹明信意义上的pastiche。无需展开术语史。'),
frame(head('DOCUMENTS / 日常权威的形式','把一本专辑，做成县城。')+`<div class="compare documents">${fig('county-records.png','《县城记》：户口簿与假报纸｜原文图三')}<div><h2>立足世界，<br><span class="red">放眼县城。</span></h2><h3>《故事会》</h3><p>杂志版式 / 小广告 / 奇情故事<br>进入歌词簿的叙事</p></div>${fig('red-document.jpg','红头文件式演出海报｜胡子设计工作室')}</div>`,'Space：户口簿拨动户籍权威；报纸翻转县城口号；故事会把杂志版式与小广告移入专辑。图三才是《县城记》，不要误认作《故事会》封面。'),
frame(head('SALON / 雅俗之间','梦幻丽莎发廊')+`<div class="compare salon">${fig('salon-front.png','发廊玻璃门式封面｜原文图四')}<div class="between">打开<i>→</i></div>${fig('salon-open.png','内页光碟成为镜面｜原文图五')}</div>`+end('戏拟“蒙娜丽莎”，让艺术与日常生活重新相遇。'),'Space：展示纸面发廊的门和唱片镜面。谈“蒙娜丽莎”的戏拟及后来装置中的真实理发活动；审美与生活边界被轻轻拨动。'),
frame(center(`<div class="eyebrow">山寨的转化 / 原文 p.108</div><h2>半地下经济行为</h2><i class="down">↓</i><h2>带有政治动能的亚文化</h2><i class="down">↓</i><h1 class="red">先锋美学</h1>`),'最后Space收束：五条人吸纳本土山寨文化，再以艺术提炼为先锋美学。转场：这些本地作品为什么又具有宽广的世界视野？')
]},
{label:'打口：地方与世界',type:'作者观点 · 课堂转述',source:'第四节 pp.108—110；“有缺口的现代性” p.109；进出口的呼应 p.110。',theme:'dark',time:'3:10',frames:[
frame(head('CIRCULATION / 获取世界的特殊路径','打口：世界从一道切口进入。')+`<div class="disc-layout"><div class="disc"><div class="hole"></div><span>DAKOU / 打口</span></div><div><div class="eyebrow">西方唱片工业</div><h2>积压<br>废弃<br>“洋垃圾”</h2><small>CD为自制机制示意</small></div></div>`,'先讲打口怎样出现：积压唱片被打上缺口，以塑料废品进入中国。唱片从内圈读取，部分内容得以保留，但切口仍可能损伤外圈曲目。'),
frame(head('MODERNITY WITH A CUT','有缺口的现代性')+`<div class="disc-layout"><div class="disc cut"><div class="hole"></div><span>DAKOU / 打口</span></div><div><h2>地下市场<br>青年 / 五条人<br><span class="red">世界音乐</span></h2><p>被作废的载体，<br>成为音乐启蒙。</p></div></div>`,'Space切口出现：西方的废弃物变成青年知识与音乐的入口。作者把回收、走私、划伤的路径概括成有缺口的现代性。'),
frame(head('GLOCALIZATION / 全球地方化','从塑料袋里看世界。')+split(fig('globe.jpg','《地球仪》真实封面｜摄影：仁科；设计：胡子'),`<h2>塑料袋<br>＋ 地球仪</h2><p>地方感与全球视野<br>相互渗透。</p><h3>《地球仪》 → 马里音乐<br>《倒港纸》 → 本土化挪用</h3>`),'Space从CD转到地球仪。地方不必被甩掉；全球与地方相互渗透。五条人从打口接触西非、中东、南美等音乐，不只看西方。'),
frame(head('LOW-END GLOBALIZATION / 作者借用并反思的概念','小北与重庆大厦：另一种全球联系')+network,'Space继续放大：《Canton Express》写外国商人在广州交易。小北、重庆大厦是低资本、非正式经济跨国流动的节点。图是关系示意，不是精确航线。'),
frame(center(`<div class="eyebrow">两条路径，在全球流动中呼应</div><div class="exchange"><span>山寨<small>商品出口 ↗</small></span><b>珠三角</b><span>打口<small>文化进口 ↙</small></span></div><h2>不止一种全球化。</h2><p>全球地方 / 低端全球化 / 全球南方</p><small>作者最终仍要反思“高 / 低”的排序。</small>`),'最后Space：原文用一出口、一进口把山寨和打口合在一起。低端全球化是讨论入口，不能把它当作作者最后接受的等级标签。')
]},
{label:'论文如何论证',type:'论证梳理 · 方法为汇报者归纳',source:'原文四节及结语；p.105明确提出山寨、打口为城中村美学的文化动因和表现方式。',theme:'paper',time:'1:50',frames:[
frame(head('02 / 结构与论证脉络','从概念出发，再回到概念。')+`<div class="argument">${flow}<aside><div class="eyebrow">原文四节</div><h3>概念界定<br>城中村美学<br>山寨中国的狂欢<br>全球地方与打口中国</h3><p>结语：理论回应</p></aside></div>`,'清楚回应老师第二项要求。这是一张课堂重构图，对应原文四节而不是三个平行盒子。山寨和打口互有层次，也在最后相互呼应。'),
frame(head('02 / 方法','用文化材料完成理论论证。')+`<div class="argument">${flow}<aside><div class="eyebrow">方法 / 我们的归纳</div><h3>个案研究<br>文化文本分析<br>社会历史材料<br>比较分析<br>理论阐释</h3><p>歌曲 / 专辑 / 海报 / Logo<br>装置 / 访谈 / 既有研究</p><small>不以问卷统计建立总体代表性。</small></aside></div>`,'Space显示方法。指出材料来自作品、访谈和既有研究；作者还直接写入海报协商过程。这不是标准问卷或统计推断论文，个案主要展示理论可能性。')
]},
{label:'文章结论',type:'作者观点 · 课堂转述',source:'摘要 p.101；结语 p.110。',theme:'paper',time:'1:30',frames:[
frame(head('03 / 文章结论','作者最终要说什么？')+`<div class="conclusion"><span>01</span><h1>“未完成”<br>并非暂时的过渡阶段。</h1><p>不以“完成”作为终极指向。</p></div>`,'明确说“下面是文章结论”。第一点：不能把未完成还原为落后阶段。'),
frame(head('03 / 文章结论','从负面标签中，看见可能。')+`<div class="conclusion"><span>02</span><h1>生长性 / 创造性<br><em>自下而上的力量</em></h1><p>城中村、烂尾楼、山寨、打口、走鬼</p><small>这些现象的潜能，不等于其中所有现实条件都值得赞美。</small></div>`,'Space第二点：重新认识负面现象中的可能性，不等于城中村或非正规劳动全是好的。'),
frame(head('03 / 文章结论','质疑一把单一的现代性标尺。')+`<div class="conclusion"><span>03</span><div class="binary">现代 / 传统　城市 / 乡村　全球 / 地方<br>美 / 丑　雅 / 俗　高 / 低　发达 / 欠发达</div><h1 class="south">GLOBAL SOUTH</h1><h2>全球南方</h2><p>对线性进化与西方中心式现代性的反拨。</p></div>`,'Space第三点：放回全球南方脉络，挑战西方或北方中心的现代性范式。转场：文章打开了视野，我们还想往前追问一步。')
]},
{label:'我们的看法',type:'我们的讨论',source:'本幕为汇报者开放性讨论；原文 pp.104、108也提到现实悲剧及治理问题。',theme:'dark',time:'1:45',frames:[
frame(head('04 / 我们的讨论','“未完成”是否可能被浪漫化？')+`<div class="debate"><div><div class="eyebrow">看到潜能</div><h2>生命力<br>创造性<br>自组织<br>包容 / 弹性</h2></div><b>?</b><div><div class="eyebrow">追问代价</div><h2>居住风险<br>非正规劳动<br>公共服务<br>结构性不平等</h2></div></div>`,'先认可文章的意义：拒绝把非正规、混杂和边缘自动当作等待淘汰的落后。然后提出风险，保持开放，不称作者忽略一切现实困境。'),
frame(center(`<div class="eyebrow">我们的讨论</div><h1>谁生活在这些空间里？<br><span class="red">谁承担风险与代价？</span></h1><p>村民房东 / 外来租客 / 流动摊贩</p><small>自组织的收益与“未完成”的成本，可能并不由同一群人承担。</small>`),'Space：给出群体差别。村民可能因租金受益，租客与摊贩面临另一套处境；这是我们的追问，不伪装成论文实证发现。可以留15秒给同学想。')
]},
{label:'联系古典社会理论',type:'我们的讨论 · 课程联系',source:'课程联系由汇报者提出；不声称作者以马克思、韦伯或齐美尔作为本文理论框架。',theme:'paper',time:'1:50',frames:[
frame(center(`<div class="eyebrow">04 / 与课程内容的联系</div><h2>古典社会理论一直在追问：</h2><h1>现代社会，<br>究竟发生了什么？</h1>`),'先共同问题，后思想家。不要从头开始重讲古典理论，也不要说作者使用了这些人的理论。'),
frame(head('THREE QUESTIONS / 三个联系线索','把课程里的问题带回来。')+`<div class="thinkers"><div><h2>马克思</h2><p>资本主义<br>商品 / 世界市场</p></div><div><h2>韦伯</h2><p>理性化<br>规则 / 现代秩序</p></div><div><h2>齐美尔</h2><p>大都市<br>货币经济 / 生活经验</p></div></div>`+end('课程联系，不是本文采用的理论框架。'),'Space：每人只讲一个联系。商品与文化的流动，正式规则与日常应对，大都市中的边缘生活经验。作者其实也用到其他理论资源，不能被这三人替代。'),
frame(center(`<div class="eyebrow">欧洲现代转型 → 珠三角经验</div><div class="keywords">城中村 / 山寨 / 打口 / 五条人</div><h1>会不会看到<br><span class="red">并不完全相同</span>的现代经验？</h1><p>让地方经验反过来追问概念的适用边界。</p>`),'Space：古典理论形成于欧洲现代转型；将同一个问题带到珠三角，是否需要重估它的尺度？保持联系而不强行套用。')
]},
{label:'回到开场',type:'我们的讨论 · 结尾',source:'末句为课堂概括；相关论据见原文 pp.102、110。',theme:'dark',time:'1:00',frames:[
frame(`<div class="montage ending"><img src="assets/images/performance.jpg" alt="回到五条人演出画面"><div class="ending-words">海丰　县城　城中村<br>塑料袋　山寨　打口<br>广州　世界</div></div><button class="replay" data-action="ending">回看片尾 12 秒 ↗</button>`,'回到真实演出画面。已放本地视频时可点击回看片尾12秒；没有视频仍用这张真实图片。按Space显示最后问题。'),
frame(center(`<div class="eyebrow">重新回到开场</div><h1>当我们说某种生活<br>“不够现代”时，<br>我们究竟在拿什么作为标准？</h1>`),'停顿，问出最后问题。不要用“谢谢观看”打断。'),
frame(center(`<h1 class="closing-question">当我们说某种生活“不够现代”时，<br>我们究竟在拿什么作为标准？</h1><div class="closing-line">未完成，不只是尚未完成；<br>它也可能意味着，不以某个既定终点作为完成。</div><small>课堂概括 · 讨论仍然开放</small>`),'再按Space显示小结。末句是根据作者观点的课堂概括，不作逐字引文。结束时可留画面进入讨论。')
]}
];

/* New-edition chapter three. The earlier chapter objects stay above only as a material archive;
   these five scenes replace them in the live sequence. */
const chapterThreeScenes=[
{label:'城中村：现代城市',type:'03 / 作者是怎么证明的？',source:'第二节 pp.102—105；上海与广州的城市治理比较。摄影：Wikimedia Commons。',theme:'paper',time:'1:35',frames:[
frame(`<section class="chapter-scene scene06"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">06</div><h1>城中村：<br><b>什么才算“现代城市”？</b></h1><div class="city-contrast"><figure class="city-view shanghai"><img src="assets/images/shanghai-lujiazui.jpg" alt="上海陆家嘴规整的现代城市天际线"><figcaption><strong>上海</strong><span>规整化的空间<br>整合城市居民身份<br>现代城市建设</span></figcaption></figure><div class="modern-question"><span>哪一个更</span><b>“现代”</b><i>？</i></div><figure class="city-view guangzhou"><img src="assets/images/guangzhou-village-city.jpg" alt="广州石牌村与现代高楼并置的城市空间"><img class="lane-inset" src="assets/images/guangzhou-village-lane.jpg" alt="广州石牌村内部街巷与居民生活"><figcaption><strong>广州</strong><span>长期保留更大的<br>弹性与自主发展空间</span></figcaption></figure></div><div class="city-choice"><p>我们想象的城市，究竟应该是——</p><div><span>“光鲜、平整、同质化”</span><i>还是</i><span>“允许杂质、毛边与旁逸斜出”</span></div></div><div class="city-tags"><span>规整的现代</span><i>/</i><span>毛边的现代<small>课堂视觉表达</small></span></div></section>`,'这不是漂亮与丑陋的比较，而是两种空间逻辑。论文以沪穗差异说明：城中村不是现代城市里等待消灭的残余，它也可能是城市化过程中的一种现实形态。“毛边的现代”只是我们帮助理解的说法。')
]},
{label:'塑料袋式生活哲学',type:'03 / 作者是怎么证明的？',source:'原文 pp.103—104；“塑料袋式的生活哲学”为作者引述设计师胡子的表达。',theme:'paper',time:'1:25',frames:[
frame(`<section class="chapter-scene scene07"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">07</div><h1>塑料袋式的生活哲学</h1><div class="rigid-city" aria-hidden="true">${Array.from({length:14},(_,i)=>`<i style="--i:${i};--h:${48+(i%5)*9}%"></i>`).join('')}</div><div class="floating-bag" aria-label="在规整高楼之间漂动的红色塑料袋"><div class="bag-handle left"></div><div class="bag-handle right"></div><div class="bag-body"><span>WUTIAOREN</span><b>塑料袋</b></div></div><div class="bag-word cheap"><b>廉价</b><span>来自日常与市井，<br>而非精英艺术。</span></div><div class="bag-word drift"><b>漂浮</b><span>没有固定位置，<br>在城市缝隙中移动。</span></div><div class="bag-word flexible"><b>柔韧</b><span>不正面对抗，<br>寻找规则之间的空间。</span></div><div class="bag-word vague"><b>暧昧</b><span>既是垃圾，<br>也可以成为诗意。</span></div><div class="shared-logic"><span>塑料袋</span><i>↓</i><span>握手楼</span><b>·</b><span>走鬼</span><b>·</b><span>城中村</span></div><div class="bag-conclusion">不正面对抗，<br><b>但拒绝被完全规整。</b></div></section>`,'把塑料袋从Logo提升为隐喻：廉价、漂浮、柔韧、暧昧。握手楼、走鬼和城中村并不相同，但共享一种在规则缝隙中移动、调整和生存的气质。动画只是环境运动，不需要按键。')
]},
{label:'山寨：模仿与创造',type:'03 / 作者是怎么证明的？',source:'第三节 pp.105—108；TIME海报、专辑与装帧案例均为项目已有论文图及真实作品图。',theme:'paper',time:'2:10',frames:[
frame(`<section class="chapter-scene scene08"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">08</div><h1>山寨：<br><b>模仿为什么也能创造？</b></h1><div class="brand-lab"><div class="brand-morph" aria-label="adidas文字逐步变形成多个山寨变体"><span>adidas</span><span>adidos</span><span>adadas</span><span>adadis</span><span>dasida</span></div><div class="brand-echoes"><i>adidos</i><i>adadas</i><i>adadis</i><i>dasida</i></div><div class="copy-create">COPY<br><em>or</em><br>CREATE<span>?</span></div></div><div class="shanzhai-archive"><figure class="archive-piece time"><img src="assets/images/time-final.png" alt="五条人哈佛讲座TIME戏仿海报"><figcaption><b>TIME → 讲座海报</b><span>改写《时代》的视觉语言</span></figcaption></figure><figure class="archive-piece stories"><img src="assets/images/stories2018.jpg" alt="五条人专辑故事会封面"><figcaption><b>《故事会》</b><span>大众读物进入音乐作品</span></figcaption></figure><figure class="archive-piece salon"><img src="assets/images/salon-front.png" alt="梦幻丽莎发廊专辑封面"><figcaption><b>蒙娜丽莎 → 发廊</b><span>经典被拉进城中村日常</span></figcaption></figure><figure class="archive-piece county"><img src="assets/images/county-records.png" alt="县城记户口簿与报纸设计"><figcaption><b>户口簿 / 文件 → 《县城记》</b><span>制度视觉变成戏谑材料</span></figcaption></figure></div><div class="transform-route"><span>模仿</span><i>→</i><span>变形</span><i>→</i><span>重新组合</span><i>→</i><b>产生新意义</b></div><div class="shanzhai-close"><p>山寨不是假装自己是“原作”，<br>而是在和“原作”游戏。</p><strong>颠覆与创造，在这里合二为一。</strong></div></section>`,'左边的品牌变体自动播放一次，说明山寨并不只是追求以假乱真。右边四组真实案例共同展示：熟悉的形式被修改、重组和戏仿，新的地方意义由此产生。')
]},
{label:'山寨的概念边界',type:'03 / 作者是怎么证明的？',source:'第三节 pp.106—108；媚俗、pastiche与山寨的区分依据论文论述整理。',theme:'paper',time:'1:55',frames:[
frame(`<section class="chapter-scene scene09"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">09</div><h1>都是“模仿”，<br><b>为什么不一样？</b></h1><div class="concept-spread"><article class="concept-entry kitsch"><div class="entry-head"><span>KITSCH</span><h2>媚俗</h2></div><p>模仿、复制、可大量获得，反对精英艺术“独一无二”的稀缺性。</p><div>可得性　复制　大众消费</div></article><article class="concept-entry pastiche"><div class="entry-head"><span>PASTICHE</span><h2>仿作 / 拼贴</h2></div><p>模仿既有风格，却可能失去戏仿原有的幽默、危险性与批判锋芒。</p><div>模仿风格　拼贴　批判性减弱</div></article><article class="concept-entry shanzhai"><div class="entry-head"><span>SHANZHAI</span><h2>山寨</h2></div><p>不一定隐藏“我是假的”；通过修改、变形、组合、戏仿，与原作进行游戏。</p><div>解构　游戏　再创造　草根可得性</div></article></div><div class="concept-verdict">五条人的“山寨”，既不是单纯的廉价复制，<br>也不是没有锋芒的空洞模仿。</div><div class="avant-route"><span>经济行为</span><i>→</i><span>亚文化</span><i>→</i><b>先锋美学</b></div><div class="avant-question">五条人的“土”，<br><b>为什么反而可能是一种先锋？</b></div></section>`,'三个概念都和模仿有关，但重点不同。媚俗强调复制对稀缺性的挑战；pastiche可能只剩风格拼贴；山寨则公开地修改和游戏，让模仿保留解构与再创造的动能。这里点到“先锋”，不展开先锋艺术理论。')
]},
{label:'打口：怎样听见世界',type:'03 / 作者是怎么证明的？',source:'第四节 pp.108—110；打口碟实物图来源见素材清单；全球南方网络为课堂关系示意。',theme:'dark',time:'2:45',frames:[
frame(`<section class="chapter-scene scene10 dakou-route"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">10</div><h1>打口：<br><b>中国怎样听见世界？</b></h1><div class="dakou-object"><img src="assets/images/dakou-disc.jpg" alt="边缘带缺口的真实打口CD"><span>真实打口碟</span></div><div class="sea-route"><div class="route-line"></div><span class="r1">西方唱片工业</span><span class="r2">库存 / 滞销</span><span class="r3">打口报废</span><span class="r4">“塑料垃圾”</span><span class="r5">进入中国</span><span class="r6">广东</span><span class="r7">走鬼 / 地摊</span><span class="r8">中国青年</span><b class="r9">五条人</b></div><div class="value-reversal"><div><small>原商品体系</small><del>垃圾</del></div><i>↘</i><div><small>中国青年手中</small><strong>音乐启蒙<br>精神食粮</strong></div></div><div class="cut-modernity"><span>MODERNITY WITH A CUT</span><h2>有缺口的现代性</h2><p>现代性不是完整地被“进口”，<br>而是在回收、走私、划伤和重新利用中被获得。</p></div><div class="space-hint">SPACE　从“西方”转向“世界”</div></section>`,'先沿着路线讲物质流动：在原商品体系中被报废的唱片，经由广东的非正式市场进入青年生活。价值发生反转，垃圾成为启蒙。这就是作者所谓“有缺口的现代性”。按一次空格再把视野从西方扩大到世界。'),
frame(`<section class="chapter-scene scene10 dakou-world"><div class="chapter-texture"></div><div class="chapter-mark">03 / 作者是怎么证明的？</div><div class="chapter-number">10</div><h1>“走向世界”<br><b>并不等于“走向西方”。</b></h1><div class="mini-dakou"><img src="assets/images/dakou-disc.jpg" alt="真实打口CD"><span>西方唱片工业 → 打口 → 广东 → 青年</span></div><div class="world-field"><svg viewBox="0 0 820 430" role="img" aria-label="以广州为节点，连接西非、中东、南亚、东南亚和南美的全球南方关系图"><path class="land l1" d="M65 80l115-35 105 28 65 65-45 52-94-15-58 42-82-52z"/><path class="land l2" d="M235 235l88 22 45 80-48 74-63-83z"/><path class="land l3" d="M390 95l125-48 173 38 74 75-88 37-58-33-85 51-106-31z"/><path class="land l4" d="M620 260l84 20 36 75-77 37-48-58z"/><g class="routes"><path d="M585 205 Q390 122 263 300"/><path d="M585 205 Q493 110 455 155"/><path d="M585 205 Q565 150 535 180"/><path d="M585 205 Q655 238 690 300"/><path d="M585 205 Q375 245 150 276"/></g><g class="nodes"><circle class="gz" cx="585" cy="205" r="12"/><circle cx="263" cy="300" r="7"/><circle cx="455" cy="155" r="7"/><circle cx="535" cy="180" r="7"/><circle cx="690" cy="300" r="7"/><circle cx="150" cy="276" r="7"/></g><g class="map-labels"><text x="600" y="198">广州</text><text x="220" y="325">西非</text><text x="410" y="145">中东</text><text x="510" y="165">南亚</text><text x="668" y="330">东南亚</text><text x="95" y="266">南美</text></g></svg><div class="local-nodes"><span>广州小北</span><span>香港重庆大厦</span><b>Canton Express</b></div><div class="sound-list">西非音乐 · 中东音乐 · 南美音乐<br>实验音乐 · 先锋摇滚 · 自由爵士</div><p>世界不只有纽约、巴黎和伦敦。</p><strong>全球与地方，不再是彼此排斥的两端。</strong></div><div class="chapter-synthesis"><div><b>城中村</b><span>空间</span></div><i>＋</i><div><b>山寨</b><span>生产 / 模仿</span></div><i>＋</i><div><b>打口</b><span>文化流动</span></div><em>→</em><h2>未完成的现代性</h2><p>三个来自珠三角的经验对象，让抽象概念成为可见的社会现实。</p></div></section>`,'第二层不是把欧美换成另一份音乐清单，而是改变“世界”的方向感：广州连向西非、中东、南亚、东南亚与南美。最后把第三章收束为三种证据：空间、文化生产和文化流动，共同让未完成的现代性变得可见。下一次空格进入文章方法。')
]}
];
scenes.splice(3,4,...chapterThreeScenes);

const chapterFourFiveScenes=[
{label:'论证地图',type:'04 / 文章怎样完成论证？',source:'依据全文论证方式归纳；并非作者另设的正式“研究方法”章节。',theme:'paper',time:'1:00',frames:[
frame(`<section class="chapter-scene scene11"><div class="chapter-texture"></div><div class="chapter-mark">04 / 站远一点看文章</div><div class="chapter-number">11</div><p class="argument-intro">从文章的论证方式来看，可以归纳出一条理论炼成路径</p><svg class="argument-path" viewBox="0 0 1460 500" preserveAspectRatio="none" aria-hidden="true"><path d="M60 405 C305 382 382 310 585 297 S885 225 1048 164 S1286 95 1400 58"/></svg><div class="argument-node case-node"><span>CASE</span><h2>五条人</h2><p>不是研究终点，<br>而是观察珠三角现代性的入口。</p></div><div class="argument-node material-node"><span>CULTURAL MATERIAL</span><h2>歌词 / 专辑 / 海报 / Logo</h2><div class="material-strip"><i>歌词</i><i>专辑</i><i>海报</i><i>Logo</i><i>装置</i><i>音乐</i></div><p>从作品、视觉设计和音乐风格中<br>提取文化意义。</p></div><div class="argument-node context-node"><span>CONTEXT</span><h2>珠三角的社会历史条件</h2><div class="context-words">改革开放　城中村　山寨产业<br>打口文化　工业化　全球化</div><p>把审美放回它产生的条件中。</p></div><div class="argument-node comparison-node"><span>COMPARISON</span><h2>比较，让地方经验成为问题</h2><div class="comparison-lines">广州 ↔ 上海<br>城中村 ↔ 贫民窟<br>小北 ↔ 重庆大厦<br>山寨 ↔ 媚俗 / pastiche<br>未完成 ↔ 欠发达 / 低端</div></div><div class="argument-node concept-node"><span>CONCEPT</span><h2>未完成的现代性</h2><p>由地方经验<br>提炼概念</p></div><div class="argument-question">从一个乐队出发，最后讨论的却是：<br><b>现代性还能不能有另一种形态？</b></div><div class="argument-summary">这是一篇通过文化个案进行社会历史解释与概念建构的论文。</div></section>`,'这篇文章没有独立的方法章节，所以这里不说作者采用了问卷或访谈等正式方法。我们只从论证方式归纳：从五条人这个个案进入，分析文化材料，放回珠三角的社会历史条件，再通过多组比较，把地方经验提升为“未完成的现代性”这一理论问题。')
]},
{label:'文章结论',type:'05 / 作者最后得出了什么？',source:'摘要 p.101；结语 p.110。',theme:'paper',time:'1:20',frames:[
frame(`<section class="chapter-scene scene12"><div class="chapter-texture"></div><div class="chapter-mark">05 / 文章结论</div><div class="chapter-number">12</div><h1>作者最后<br><b>得出了什么？</b></h1><div class="old-binaries"><small>我们习惯这样分类世界。</small><span>现代　/　传统</span><span>城市　/　乡村</span><span>全球　/　本土</span><span>文明　/　落后</span><span>雅　/　俗</span><span>美　/　丑</span><span>高　/　低</span></div><div class="mixed-relations"><span>城市 <i>×</i> 乡村</span><span>本土 <i>×</i> 全球</span><span>雅 <i>×</i> 俗</span><span>高 <i>×</i> 低</span><p>五条人揭示的，不是哪一边胜利，<br>而是边界可以共存、交错、重组。</p></div><div class="final-findings"><article><b>01</b><p>城中村、山寨和打口，<br><strong>不是落后现代性的残余。</strong></p></article><article><b>02</b><p>它们是中国获取和诠释现代性的<br><strong>特殊方式。</strong></p></article><article><b>03</b><p>由此，文章叩问了以<br><strong>西方 / 北方为中心的现代性范式。</strong></p></article></div><div class="final-statement"><p>“未完成”不是尚未抵达终点，<br><b>而是拒绝把“完成”当作唯一标准。</b></p><h2>未完成的现代性</h2><span>UNFINISHED MODERNITY</span></div></section>`,'这一页明确回答文章结论。第一，三个经验对象不是现代化失败后留下的残余；第二，它们本身就是中国获取和诠释现代性的特殊方式；第三，这种地方经验让以西方或北方为中心的单一范式受到追问。重点不只是打破二元，而是拒绝把“完成”当作唯一标准。')
]}
];
scenes.splice(8,2,...chapterFourFiveScenes);

const closingDiscussionScenes=[
{label:'古典问题的新地点',type:'06 / 回到古典社会理论',source:'课程关联由汇报者提出；不声称本文以三位古典理论家为直接理论框架。',theme:'paper',time:'0:55',frames:[
frame(`<section class="chapter-scene scene13"><div class="chapter-texture"></div><div class="chapter-mark">06 / 回到古典社会理论</div><div class="chapter-number">13</div><h1>从十九世纪欧洲，<br><b>到二十一世纪珠三角</b></h1><div class="two-modernities europe"><span>19世纪欧洲</span><h2>工业化<br>资本主义<br>大都市<br>市场扩张<br>传统秩序变化</h2><div>马克思　韦伯　齐美尔</div></div><div class="shared-question"><small>古典社会学不断追问</small><strong>现代社会<br>到底发生了什么？</strong><i>→</i></div><div class="two-modernities delta"><span>改革开放后的珠三角</span><h2>世界工厂<br>城中村<br>流动人口<br>山寨产业<br>全球文化流动</h2><div>五条人</div></div><div class="theory-bridge"><p>古典社会学与这篇文章共享同一个问题——</p><b>如何理解现代性的社会后果。</b><strong>古典社会理论提出的问题没有消失，<br>只是换了一个地点。</strong></div></section>`,'这一页不复习三位理论家的知识点，只建立课程联系。马克思、韦伯和齐美尔面对的是十九世纪欧洲的资本主义、工业化与城市秩序变化；林峥面对的是改革开放后的珠三角。地点变了，但“现代社会发生了什么”这个问题没有消失。')
]},
{label:'把古典问题带到珠三角',type:'06 / 回到古典社会理论',source:'本页为课程联系：以马克思、韦伯、齐美尔的问题意识理解珠三角材料。',theme:'paper',time:'1:20',frames:[
frame(`<section class="chapter-scene scene14"><div class="chapter-texture"></div><div class="chapter-mark">06 / 回到古典社会理论</div><div class="chapter-number">14</div><h1>把古典问题带到珠三角，<br><b>会得到什么？</b></h1><div class="thinker-lines"><article class="thinker marx"><span>马克思</span><h2>资本主义与现代社会</h2><h3>资本主义现代化会把<br>“落后”空间消灭掉吗？</h3><p>城中村以低成本居住空间承载外来劳动者，同时参与支撑珠三角“世界工厂”。</p><strong>“现代”与“不现代”，<br>可能彼此依存。</strong></article><article class="thinker weber"><span>韦伯</span><h2>理性化与现代秩序</h2><h3>现代社会是否一定越来越<br>正规、理性、可计算？</h3><p>握手楼与走鬼，呈现的是正式规则边缘、制度缝隙中的行动逻辑。</p><strong>规则是否也会不断生产<br>新的绕行方式？</strong></article><article class="thinker simmel"><span>齐美尔</span><h2>大都市与现代生活</h2><h3>现代都市会塑造怎样的<br>生活经验？</h3><p>握手楼、发廊、走鬼、大排档、塑料袋，构成另一种都市感受。</p><strong>如果齐美尔面对的是柏林，<br>广州城中村会产生怎样的<br>“大都市与精神生活”？</strong></article></div><div class="classical-close">古典社会理论提供问题，<b>珠三角经验改变答案。</b></div></section>`,'马克思提醒我们看到城中村与世界工厂的依存关系；韦伯的问题让我们追问正式规则如何同时产生绕行空间；齐美尔则帮助我们把握城中村独特的都市生活经验。这不是用三位理论家替代论文，而是把他们的问题带到珠三角继续问。')
]},
{label:'真的摆脱西方中心吗',type:'07 / 我们的看法',source:'本页为汇报者提出的讨论；“前沿外国音乐”“甚至根本不需要被完成”见论文相关论述。',theme:'paper',time:'1:05',frames:[
frame(`<section class="chapter-scene scene15"><div class="chapter-texture"></div><div class="chapter-mark">07 / 我们的看法</div><div class="chapter-number">15</div><h1>真的摆脱了<br><b>西方中心吗？</b></h1><div class="decenter-question">去中心化，<br><b>为什么这么难？</b></div><div class="evidence foreign"><span>证据一 / 打口</span><blockquote>“接触小众、前沿外国音乐的精神食粮”</blockquote><h2>谁定义“前沿”？</h2><div class="implicit-arrow">外国 / 前沿 <i>→</i> 中国 / 接收</div><p>作者试图去中心化，但某些语言仍可能延续中心—边缘的评价习惯。</p></div><div class="evidence unfinished-word"><span>证据二 / 概念</span><h2>“未完成”</h2><div class="word-associations">尚未完成？　还在半路？<br>距离“完成”还有多远？</div><blockquote>“甚至根本不需要被完成。”</blockquote><p>为了否定“完成论”的概念，为什么仍需借助“完成 / 未完成”的语言？</p></div><div class="critical-close"><strong>作者改变了答案，</strong><br>但是否彻底改变了那把提问的尺子？<small>讨论方向：“生成中的现代性”“开放的现代性”是否会更准确？</small></div></section>`,'这是我们的第一个批评，不是说作者完全没有摆脱西方中心。更准确的说法是：她努力改变中心化的答案，但“前沿外国音乐”与“未完成”仍可能携带旧尺度。重点是追问：去中心化为什么如此困难？替代命名只作为讨论，不替作者改写概念。')
]},
{label:'可能性是谁的可能性',type:'07 / 我们的看法',source:'本页后半为汇报者进一步提出的社会学问题，不作为林峥原文结论。',theme:'paper',time:'1:10',frames:[
frame(`<section class="chapter-scene scene16"><div class="chapter-texture"></div><div class="chapter-mark">07 / 我们的看法</div><div class="chapter-number">16</div><h1>“可能性”，<br><b>是谁的可能性？</b></h1><div class="possibility-side"><span>可能性</span><h2>活力<br>创造<br>弹性<br>自组织<br>低成本空间</h2><p>艺术家 / 文化生产者<br>可能把非正规经验<br>转化为作品与美学。</p></div><div class="who-core"><strong>谁？</strong><p>同一个“未完成”，<br>对不同位置的人<br>意味着不同的东西。</p></div><div class="cost-side"><span>代价</span><h2>不稳定<br>拥挤<br>制度性不确定<br>日常生存压力</h2><p>租客 / 普通摊贩<br>可能首先把非正规性<br>作为生活条件来承受。</p></div><div class="position-contrast"><div><b>观看握手楼的人</b><span>建筑冲击 / 城中村美学</span></div><i>≠</i><div><b>每天住在里面的人</b><span>具体而持续的居住条件</span></div></div><div class="possibility-close"><p>当我们把非正规性重新发现为一种美学时，也要追问：</p><strong>谁有能力把它变成美学，谁必须把它当作生活？</strong><small>“未完成”的可能性与代价，是如何在不同人之间分配的？</small></div></section>`,'文章把负面对象重新发现为可能性，这一点很重要。社会学还要再问一步：谁能把非正规性转化为创造力，谁必须承受它带来的不稳定？这不是说城中村只有坏处，而是提醒我们，同一种“未完成”的收益与代价可能分配给不同的人。')
]}
];
scenes.splice(10,2,...closingDiscussionScenes);
