'use strict';
(()=>{
const $=id=>document.getElementById(id), stage=$('stage'), article=$('content'), video=$('video'), info=$('info'), lightbox=$('lightbox');
let scene=0,step=0,videoActive=false,inlineVideoActive=false,ending=false,loadTimer=null,sequenceTimer=null,toastTimer=null,mediaToken=0;
const lengths=scenes.map(s=>s.frames.length),total=lengths.reduce((a,b)=>a+b,0),lastScene=scenes.length-1;
function resize(){const z=Math.min(innerWidth/1600,innerHeight/900);stage.style.transform=`scale(${z})`;stage.style.left=(innerWidth-1600*z)/2+'px';stage.style.top=(innerHeight-900*z)/2+'px';}addEventListener('resize',resize);resize();
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;toastTimer=setTimeout(()=>$('toast').textContent='',6000);}
function stopMedia(){mediaToken++;clearTimeout(loadTimer);clearTimeout(sequenceTimer);loadTimer=sequenceTimer=null;videoActive=false;video.pause();const inline=article.querySelector('.intro-inline-video');if(inline)inline.pause();inlineVideoActive=false;$('video-layer').hidden=true;}
function render(){const s=scenes[scene];stage.className=s.theme;stage.dataset.scene=scene;stage.dataset.step=step;$('scene-label').textContent=`${String(scene).padStart(2,'0')} / ${s.label}`;$('viewpoint').textContent=s.type;$('citation').textContent=s.source;$('counter').textContent=`${String(scene).padStart(2,'0')} / ${String(lastScene).padStart(2,'0')} · ${step+1}/${lengths[scene]}`;article.classList.remove('enter');article.innerHTML=s.frames[step].html;void article.offsetWidth;article.classList.add('enter');$('notes').textContent=s.frames[step].note;const n=lengths.slice(0,scene).reduce((a,b)=>a+b,0)+step;$('progress').style.width=(100*n/(total-1))+'%';document.querySelectorAll('[data-jump]').forEach(b=>{b.classList.toggle('current',+b.dataset.jump===scene);b.setAttribute('aria-current',+b.dataset.jump===scene?'step':'false');});try{history.replaceState(null,'',`#${String(scene).padStart(2,'0')}.${step}`);}catch{} }
function go(s,k=0){stopMedia();scene=Math.max(0,Math.min(scenes.length-1,s));step=Math.max(0,Math.min(lengths[scene]-1,k));$('notes').hidden=true;render();}
function next(){if(info.open||lightbox.open)return;if(videoActive){finishVideo();return;}if(scene===0&&step===0){begin();return;}if(step<lengths[scene]-1)go(scene,step+1);else if(scene<scenes.length-1)go(scene+1);}
function back(){if(info.open||lightbox.open)return;if(step>0)go(scene,step-1);else if(scene>0)go(scene-1,lengths[scene-1]-1);}
function fallback(isEnding){stopMedia();toast('未检测到可播放的本地视频，使用真实图像导入；按 → 可继续。');sequenceTimer=setTimeout(()=>{if(isEnding&&scene===lastScene&&step===0)go(lastScene,1);else if(!isEnding&&scene===0&&step===1)go(0,2);},isEnding?12000:50000);}
function finishVideo(){const target=ending?lastScene:0;go(target,ending?1:2);}
async function playVideo(isEnding){stopMedia();ending=isEnding;const token=mediaToken;videoActive=true;$('video-layer').hidden=false;$('video-layer').querySelector('.video-words').textContent='';video.onloadedmetadata=async()=>{if(token!==mediaToken)return;clearTimeout(loadTimer);video.currentTime=isEnding?Math.max(0,video.duration-12):0;try{await video.play();}catch{if(token===mediaToken){stopMedia();toast('浏览器未开始播放；可使用图片导入，或再次点击播放。');}}};video.onerror=()=>{if(token===mediaToken)fallback(isEnding);};video.src='assets/video/opening.mp4';video.load();loadTimer=setTimeout(()=>{if(token===mediaToken&&video.readyState<2)fallback(isEnding);},4500);}
function begin(){go(0,1);}
async function playInlineIntro(){const player=article.querySelector('.intro-inline-video'),trigger=article.querySelector('.intro-video-trigger');if(!player)return;player.hidden=false;if(trigger)trigger.hidden=true;inlineVideoActive=true;player.onended=()=>{inlineVideoActive=false;toast('视频播放结束，按 → 继续。');};try{await player.play();}catch{inlineVideoActive=false;player.hidden=true;if(trigger)trigger.hidden=false;toast('视频未能开始播放，请再次点击播放按钮。');}}
function toggleInlineVideo(){const player=article.querySelector('.intro-inline-video');if(!player||player.hidden)return;if(player.paused){player.play().then(()=>inlineVideoActive=true).catch(()=>toast('视频无法继续播放。'));}else player.pause();}
function toggleVideo(){if(!videoActive)return;if(video.paused)video.play().catch(()=>toast('视频无法播放；按 → 跳过。'));else video.pause();}
video.addEventListener('ended',()=>{if(videoActive)finishVideo();});video.addEventListener('click',toggleVideo);video.addEventListener('timeupdate',()=>{if(!videoActive)return;if(!ending&&video.currentTime>=55){finishVideo();return;}const words=ending?['海丰','县城','城中村','塑料袋','山寨','打口','广州','世界']:['海丰','县城','方言','广州','城中村'];const elapsed=ending?video.currentTime-Math.max(0,video.duration-12):video.currentTime;const idx=Math.min(words.length-1,Math.floor(elapsed/(ending?1.5:10)));$('video-layer').querySelector('.video-words').textContent=words[Math.max(0,idx)];});$('play-pause').onclick=toggleVideo;$('skip-video').onclick=finishVideo;
article.addEventListener('click',e=>{const b=e.target.closest('button');if(b){if(b.dataset.action==='start')begin();else if(b.dataset.action==='intro-video')playInlineIntro();else if(b.dataset.action==='ending')playVideo(true);else if(b.dataset.image){lightbox.querySelector('img').src='assets/images/'+b.dataset.image;lightbox.querySelector('img').alt=b.dataset.caption;lightbox.querySelector('p').textContent=b.dataset.caption;lightbox.showModal();}return;}if(e.target.matches('.intro-inline-video'))toggleInlineVideo();else if(e.target.closest('.observation-page'))next();});
article.addEventListener('pointermove',e=>{const bag=article.querySelector('.floating-bag');if(!bag)return;const r=article.getBoundingClientRect();bag.style.setProperty('--mx',((e.clientX-r.left)/r.width-.5)*18+'px');bag.style.setProperty('--my',((e.clientY-r.top)/r.height-.5)*10+'px');});
scenes.forEach((s,i)=>{const b=document.createElement('button');b.dataset.jump=i;b.textContent=String(i).padStart(2,'0');b.title=s.label;b.setAttribute('aria-label',`跳转 ${i} ${s.label}`);b.onclick=()=>go(i);$('chapters').append(b);});$('back').onclick=back;$('next').onclick=next;
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('本浏览器不支持网页全屏，可尝试 F11。');}}$('fullscreen').onclick=full;$('help').onclick=()=>info.showModal();
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'){if(lightbox.open)lightbox.close();else if(info.open)info.close();else if(videoActive)finishVideo();else if(inlineVideoActive){const player=article.querySelector('.intro-inline-video');if(player)player.pause();inlineVideoActive=false;}else if(sequenceTimer){const target=scene===lastScene?lastScene:0;go(target,target===lastScene?1:2);}else $('notes').hidden=true;return;}if(info.open||lightbox.open)return;if([' ','ArrowRight','ArrowLeft','f','F','h','H','n','N'].includes(e.key))e.preventDefault();if(e.key===' '){videoActive?toggleVideo():inlineVideoActive?toggleInlineVideo():next();}else if(e.key==='ArrowRight')next();else if(e.key==='ArrowLeft')back();else if(e.key.toLowerCase()==='f')full();else if(e.key.toLowerCase()==='h')info.showModal();else if(e.key.toLowerCase()==='n')$('notes').hidden=!$('notes').hidden;});
const m=location.hash.match(/^#(\d+)\.(\d+)$/);if(m){scene=Math.min(lastScene,+m[1]);step=Math.min(lengths[scene]-1,+m[2]);}render();
})();
